trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    mvn clean package
  displayName: "Building Don's DevOps App"

- script: |
    mvn clean test
  displayName: "Testing Azure DevOps App"

- script: |
    mvn clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=dondoncorre22 -Dsonar.projectKey=dondoncorre22_dondoncorre22 -Dsonar.token=c09818093d354bef71fdbb3b3a94a3815bc02fbb
  displayName: "Integrate SAST using SonarCloud in Azure DevOps DevSecOps Pipeline"
