trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: "SECURE_TOKENS"
- name: sonar_token
  value: $[variables.SONARTOKEN]

steps:
- script: |
    echo "This is a demo YAML file for DevSecOps Pipeline"
  displayName: "Print Console Text for Demo"

steps:
- script: |
    mvn clean package
  displayName: "Building Don's DevOps App"

- script: |
    mvn clean test
  displayName: "Testing Don's DevOps App"

- script: |
    mvn clean verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=dondoncorre22 -Dsonar.projectKey=dondoncorre22_dondoncorre22 -Dsonar.token=$(sonar_token)
  displayName: "Integrate SAST using SonarCloud in Azure DevOps DevSecOps Pipeline"

- script: |
    mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=dondoncorre22 -Dsonar.projectKey=dondoncorre22_dondoncorre22 -Dsonar.token=$(sonar_token)
  displayName: "Integrate SAST using SonarCloud in Azure DevOps DevSecOps Pipeline"

- script: |
    sleep 5
    sudo apt update
    sudo apt install curl jq 
    quality_status=$(curl -s -u c09818093d354bef71fdbb3b3a94a3815bc02fbb: https://sonarcloud.io/api/qualitygates/project_status?projectKey=dondoncorre22_dondoncorre22 | jq -r '.projectStatus.status')
    echo "SonarCloud Analysis Status is $quality_status"; 
    if [[ $quality_status == "ERROR" ]] ; then exit 1;fi
  displayName: "Integrate SAST using SonarCloud with Quality Gates in Pipeline"
